- name: restart postgres
  service: name=postgresql state=restarted
  become: yes

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  become: yes
  
- name: restart gunicorn
  service: name=gunicorn state=restarted enabled=yes
  become: yes
