##
# Restart gunicorn and nginx
##

- name: restart gunicorn
  service: 
    name: gunicorn
    state: restarted
    enabled: yes
  become: yes
  
- name: restart nginx
  service:
    name: nginx 
    state: restarted 
    enabled: yes
  become: yes
  

