##
# Configure the server for the Django app
##
- include: 01_server.yml
- include: 02_git.yml
- include: 03_dependencies.yml
- include: 04_postgres.yml
- include: 05_spa.yml
- include: 06_migrations.yml
- include: 07_nginx.yml
- include: 08_gunicorn.yml
